services:
  - type: web
    name: atbash-api
    runtime: node
    region: singapore # or oregon, frankfurt, ohio
    plan: free # or starter, standard
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRIV_KEY
        sync: false # set manually in dashboard
      - key: PRIV_KEY_EC
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
